version: '3.8'

services:
  it-sim-game:
    container_name: it-sim-game
    build: .
    ports:
      - "5001:5000"  # Map host port 5001 to container port 5000
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
